services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    environment: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - 3306

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    environment: .env
    ports:
      - 8443:443
    restart: on-failure

  wordpress:
    container_name: wordpress
    environment: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: on-failure
    expose: 
      - 9000

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /goinfre/dgoubin/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none 
      o: bind
      device: /goinfre/dgoubin/data/mariadb

networks:
  inception:
    driver: bridge