version: "3"
			services:
			nginx:
          build: requirements/website/ 
          env_file: .env
          container_name: website
				ports:
				- "80:80"
				restart: always
			nginx:
				build: requirements/intra/
				env_file: .env
				container_name: intra
				ports:
				- "80:80"
				restart: always 
			mariadb:
				container_name: badgeuse
				build: mariadb
				env_file: .env
				restart: always
					